name: Auto Update Posts

on:
  repository_dispatch:
    types: [update_posts]

jobs:
  update_posts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Update JSON files
        run: |
          echo '${{ toJSON(github.event.client_payload.data) }}' > ${{ github.event.client_payload.section }}_posts.json
          
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git add .
          git commit -m "Actualización automática: ${{ github.event.client_payload.section }}"
          git push
